spring:
  application.name: spring-batch
  datasource:
    url: jdbc:mysql://localhost:3306/springbatch?useSSL=false&allowPublicKeyRetrieval=true
    username: springbatch
    password: password
  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    root: INFO
    '[com.infybuzz.springbatch]': DEBUG
