spring:
  application.name: spring-batch
  datasource:
    url: jdbc:mysql://localhost:3306/springbatch
    username: springbatch
    password: password
  batch:
    jdbc:
      initialize-schema: always
