spring:
  application.name: spring-batch
  datasource:
    url: jdbc:mysql://localhost:3306/springbatch?useSSL=false&allowPublicKeyRetrieval=true
    username: springbatch
    password: password
    university:
      url: jdbc:mysql://localhost:3306/university?useSSL=false&allowPublicKeyRetrieval=true
      username: university
      password: password

  main:
    web-application-type: none
  batch:
    job:
      name: Chunk job
#       enabled: false
#     jdbc:
#       initialize-schema: always

logging:
  level:
    root: INFO
    '[com.infybuzz.springbatch]': DEBUG
